# Generated by Django 6.1.1 on 2026-10-07 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_account_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gcp', 'Google Cloud'), ('aws', 'AWS'), ('azure', 'Azure')], max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('is_open', models.BooleanField(default=True)),
                ('pubsub_subscription', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_billing_account')],
            },
        ),
        migrations.CreateModel(
            name='AccountBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_enabled', models.BooleanField(default=False)),
                ('project_number', models.CharField(blank=True, default='', max_length=50)),
                ('synced_at', models.DateTimeField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='accounts.account')),
                ('billing_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_links', to='billing.billingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('period', models.CharField(blank=True, choices=[('month', 'Monthly'), ('quarter', 'Quarterly'), ('year', 'Yearly'), ('custom', 'Custom')], default='', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('credit_treatment', models.CharField(blank=True, default='', max_length=50)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('has_other_filters', models.BooleanField(default=False)),
                ('pubsub_topic', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='billing.billingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('interval_start', models.DateTimeField()),
                ('threshold_exceeded', models.FloatField(blank=True, null=True)),
                ('forecast_threshold_exceeded', models.FloatField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='billing.budget')),
            ],
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('billing_account', 'external_id'), name='unique_billing_budget'),
        ),
        migrations.AddIndex(
            model_name='budgetstatus',
            index=models.Index(fields=['budget', '-published_at'], name='billing_bud_budget__9762e7_idx'),
        ),
    ]
