# Generated by Django 6.1.1 on 2026-10-08 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0002_clusters_unique_account_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespaces', models.JSONField(default=list)),
                ('mode', models.CharField(choices=[('cutover', 'Cutover'), ('copy', 'Copy')], default='cutover', max_length=20)),
                ('storage_class_mapping', models.JSONField(blank=True, default=dict)),
                ('storage_location', models.CharField(default='default', max_length=253)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checking', 'Checking'), ('scaling_down', 'Scaling down the source'), ('backing_up', 'Backing up'), ('restoring', 'Restoring'), ('scaling_up', 'Scaling up the target'), ('verifying', 'Verifying'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('waiting_on', models.TextField(blank=True, default='')),
                ('failed_step', models.CharField(blank=True, choices=[('pending', 'Pending'), ('checking', 'Checking'), ('scaling_down', 'Scaling down the source'), ('backing_up', 'Backing up'), ('restoring', 'Restoring'), ('scaling_up', 'Scaling up the target'), ('verifying', 'Verifying'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('backup_name', models.CharField(blank=True, default='', max_length=253)),
                ('restore_name', models.CharField(blank=True, default='', max_length=253)),
                ('replicas', models.JSONField(blank=True, default=dict)),
                ('step_started_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_out', to='clusters.clusters')),
                ('target_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_in', to='clusters.clusters')),
            ],
        ),
        migrations.CreateModel(
            name='MoveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='moves.move')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='move',
            constraint=models.CheckConstraint(condition=models.Q(('source_cluster', models.F('target_cluster')), _negated=True), name='move_between_two_clusters'),
        ),
    ]
