# Generated by Django 6.0.9 on 2026-10-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='method',
            field=models.CharField(choices=[('velero', 'Velero'), ('manifests', 'Manifests only')], default='velero', max_length=20),
        ),
        migrations.AlterField(
            model_name='move',
            name='failed_step',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('checking', 'Checking'), ('scaling_down', 'Scaling down the source'), ('backing_up', 'Backing up'), ('restoring', 'Restoring'), ('copying', 'Copying manifests'), ('scaling_up', 'Scaling up the target'), ('verifying', 'Verifying'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='move',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checking', 'Checking'), ('scaling_down', 'Scaling down the source'), ('backing_up', 'Backing up'), ('restoring', 'Restoring'), ('copying', 'Copying manifests'), ('scaling_up', 'Scaling up the target'), ('verifying', 'Verifying'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
