"""
Django settings for cloudhop project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-gi@^cjm0^_1w38xwc(j7sphroo2gc1q%9m+5s_k^*ow$2bbui-')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

# Comma-separated; with DEBUG and none set, Django allows localhost
ALLOWED_HOSTS = [host for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if host]

# The Vue dev server (frontend/) proxies /api here; its origin must pass the CSRF check
CSRF_TRUSTED_ORIGINS = ["http://localhost:5173", "http://127.0.0.1:5173"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'clusters',
    'kubernetes',
    'billing',
    'moves'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves the admin's and DRF's static files when gunicorn runs the app
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cloudhop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cloudhop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Primary key used by every model that does not declare one
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Where uploaded cloud credential files are stored (kept out of git)
CREDENTIALS_DIR = BASE_DIR / "credentials"

# The defaults match the postgres service in compose.yaml, published on localhost
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'cloudhop'),
        'USER': os.environ.get('POSTGRES_USER', 'cloudhop'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'cloudhop'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# collectstatic copies them here, for whitenoise
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Celery: syncs clusters, resources and billing in the background (run a worker with --beat)

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
# Nothing reads task results; failures are logged by the worker
CELERY_TASK_IGNORE_RESULT = True
CELERY_TIMEZONE = TIME_ZONE

# Minutes between scheduled syncs; a queued sync not started by the next run is dropped
SYNC_INTERVAL_MINUTES = 15
CELERY_BEAT_SCHEDULE = {
    "sync-clusters": {
        "task": "clusters.tasks.sync_all_clusters",
        "schedule": crontab(minute=f"*/{SYNC_INTERVAL_MINUTES}"),
    },
    "sync-resources": {
        "task": "kubernetes.tasks.sync_all_resources",
        "schedule": crontab(minute=f"*/{SYNC_INTERVAL_MINUTES}"),
    },
    "sync-billing": {
        "task": "billing.tasks.sync_all_billing",
        "schedule": crontab(minute=f"*/{SYNC_INTERVAL_MINUTES}"),
    },
    # Moves run step by step on their own; this picks up any whose next run was lost
    "resume-moves": {
        "task": "moves.tasks.resume_moves",
        "schedule": crontab(minute="*/5"),
    },
}
