# Generated by Django 6.1.1 on 2026-10-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('gcp', 'Google Cloud'), ('aws', 'AWS'), ('azure', 'Azure')], max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('credential_ref', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_cloud_account')],
            },
        ),
    ]
