# Generated by Django 6.1.1 on 2026-10-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='project_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
