# Generated by Django 6.1.1 on 2026-10-06 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0002_clusters_unique_account_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, default='', max_length=253)),
                ('version', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=100)),
                ('namespace', models.CharField(blank=True, default='', max_length=253)),
                ('name', models.CharField(max_length=253)),
                ('uid', models.CharField(max_length=64)),
                ('manifest', models.JSONField(default=dict)),
                ('status', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('kube_created_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='clusters.clusters')),
            ],
            options={
                'indexes': [models.Index(fields=['cluster', 'kind'], name='kubernetes__cluster_af13e8_idx'), models.Index(fields=['cluster', 'namespace'], name='kubernetes__cluster_9c89c7_idx')],
                'constraints': [models.UniqueConstraint(fields=('cluster', 'group', 'kind', 'namespace', 'name'), name='unique_cluster_resource')],
            },
        ),
    ]
