# Generated by Django 6.1.1 on 2026-10-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubernetes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kuberesource',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='kuberesource',
            name='last_seen_at',
        ),
        migrations.RemoveField(
            model_name='kuberesource',
            name='updated_at',
        ),
    ]
