# Generated by Django 6.1.1 on 2026-10-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_project_id'),
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clusters',
            constraint=models.UniqueConstraint(fields=('account_id', 'external_id'), name='unique_account_cluster'),
        ),
    ]
